// Pretty sure Clustering was eventually removed from ATS, but on our version
// it looks like the metrics are still hanging around. These might be useful
// for someone else.
type ClusterCounters struct {
    proxy_node_cluster_nodes                                             float64 `json:"proxy.node.cluster.nodes"`
    ProxyProcessClusterConnectionsOpen                         float64 `json:"proxy.process.cluster.connections_open"`
    ProxyProcessClusterConnectionsOpened                       float64 `json:"proxy.process.cluster.connections_opened"`
    ProxyProcessClusterConnectionsClosed                       float64 `json:"proxy.process.cluster.connections_closed"`
    ProxyProcessClusterSlowCtrlMsgsSent                        float64 `json:"proxy.process.cluster.slow_ctrl_msgs_sent"`
    ProxyProcessClusterConnectionsReadLocked                   float64 `json:"proxy.process.cluster.connections_read_locked"`
    ProxyProcessClusterConnectionsWriteLocked                  float64 `json:"proxy.process.cluster.connections_write_locked"`
    ProxyProcessClusterReads                                   float64 `json:"proxy.process.cluster.reads"`
    ProxyProcessClusterReadBytes                               float64 `json:"proxy.process.cluster.read_bytes"`
    ProxyProcessClusterWrites                                  float64 `json:"proxy.process.cluster.writes"`
    ProxyProcessClusterWriteBytes                              float64 `json:"proxy.process.cluster.write_bytes"`
    ProxyProcessClusterControlMessagesSent                     float64 `json:"proxy.process.cluster.control_messages_sent"`
    ProxyProcessClusterControlMessagesReceived                 float64 `json:"proxy.process.cluster.control_messages_received"`
    ProxyProcessClusterOpDelayedForLock                        float64 `json:"proxy.process.cluster.op_delayed_for_lock"`
    ProxyProcessClusterConnectionsBumped                       float64 `json:"proxy.process.cluster.connections_bumped"`
    ProxyProcessClusterNetBackup                               float64 `json:"proxy.process.cluster.net_backup"`
    ProxyProcessClusterNodes                                   float64 `json:"proxy.process.cluster.nodes"`
    ProxyProcessClusterMachinesAllocated                       float64 `json:"proxy.process.cluster.machines_allocated"`
    ProxyProcessClusterMachinesFreed                           float64 `json:"proxy.process.cluster.machines_freed"`
    ProxyProcessClusterConfigurationChanges                    float64 `json:"proxy.process.cluster.configuration_changes"`
    ProxyProcessClusterDelayedReads                            float64 `json:"proxy.process.cluster.delayed_reads"`
    ProxyProcessClusterByteBankUsed                            float64 `json:"proxy.process.cluster.byte_bank_used"`
    ProxyProcessClusterAllocDataNews                           float64 `json:"proxy.process.cluster.alloc_data_news"`
    ProxyProcessClusterWriteBbMallocs                          float64 `json:"proxy.process.cluster.write_bb_mallocs"`
    ProxyProcessClusterPartialReads                            float64 `json:"proxy.process.cluster.partial_reads"`
    ProxyProcessClusterPartialWrites                           float64 `json:"proxy.process.cluster.partial_writes"`
    ProxyProcessClusterCacheOutstanding                        float64 `json:"proxy.process.cluster.cache_outstanding"`
    ProxyProcessClusterRemoteOpTimeouts                        float64 `json:"proxy.process.cluster.remote_op_timeouts"`
    ProxyProcessClusterRemoteOpReplyTimeouts                   float64 `json:"proxy.process.cluster.remote_op_reply_timeouts"`
    ProxyProcessClusterChanInuse                               float64 `json:"proxy.process.cluster.chan_inuse"`
    ProxyProcessClusterOpenDelays                              float64 `json:"proxy.process.cluster.open_delays"`
    ProxyProcessClusterConnectionsAvgTime                      float64 `json:"proxy.process.cluster.connections_avg_time"`
    ProxyProcessClusterControlMessagesAvgSendTime              float64 `json:"proxy.process.cluster.control_messages_avg_send_time"`
    ProxyProcessClusterControlMessagesAvgReceiveTime           float64 `json:"proxy.process.cluster.control_messages_avg_receive_time"`
    ProxyProcessClusterOpenDelayTime                           float64 `json:"proxy.process.cluster.open_delay_time"`
    ProxyProcessClusterCacheCallbackTime                       float64 `json:"proxy.process.cluster.cache_callback_time"`
    ProxyProcessClusterRmtCacheCallbackTime                    float64 `json:"proxy.process.cluster.rmt_cache_callback_time"`
    ProxyProcessClusterLkrmtCacheCallbackTime                  float64 `json:"proxy.process.cluster.lkrmt_cache_callback_time"`
    ProxyProcessClusterLocalConnectionTime                     float64 `json:"proxy.process.cluster.local_connection_time"`
    ProxyProcessClusterRemoteConnectionTime                    float64 `json:"proxy.process.cluster.remote_connection_time"`
    ProxyProcessClusterRdmsgAssembleTime                       float64 `json:"proxy.process.cluster.rdmsg_assemble_time"`
    ProxyProcessClusterClusterPingTime                         float64 `json:"proxy.process.cluster.cluster_ping_time"`
    ProxyProcessClusterCacheCallbacks                          float64 `json:"proxy.process.cluster.cache_callbacks"`
    ProxyProcessClusterRmtCacheCallbacks                       float64 `json:"proxy.process.cluster.rmt_cache_callbacks"`
    ProxyProcessClusterLkrmtCacheCallbacks                     float64 `json:"proxy.process.cluster.lkrmt_cache_callbacks"`
    ProxyProcessClusterLocalConnectionsClosed                  float64 `json:"proxy.process.cluster.local_connections_closed"`
    ProxyProcessClusterRemoteConnectionsClosed                 float64 `json:"proxy.process.cluster.remote_connections_closed"`
    ProxyProcessClusterSetdataNoClustervc                      float64 `json:"proxy.process.cluster.setdata_no_clustervc"`
    ProxyProcessClusterSetdataNoTunnel                         float64 `json:"proxy.process.cluster.setdata_no_tunnel"`
    ProxyProcessClusterSetdataNoCachevc                        float64 `json:"proxy.process.cluster.setdata_no_cachevc"`
    ProxyProcessClusterSetdataNoCluster                        float64 `json:"proxy.process.cluster.setdata_no_cluster"`
    ProxyProcessClusterVcWriteStall                            float64 `json:"proxy.process.cluster.vc_write_stall"`
    ProxyProcessClusterNoRemoteSpace                           float64 `json:"proxy.process.cluster.no_remote_space"`
    ProxyProcessClusterLevel1Bank                              float64 `json:"proxy.process.cluster.level1_bank"`
    ProxyProcessClusterMultilevelBank                          float64 `json:"proxy.process.cluster.multilevel_bank"`
    ProxyProcessClusterVcCacheInsertLockMisses                 float64 `json:"proxy.process.cluster.vc_cache_insert_lock_misses"`
    ProxyProcessClusterVcCacheInserts                          float64 `json:"proxy.process.cluster.vc_cache_inserts"`
    ProxyProcessClusterVcCacheLookupLockMisses                 float64 `json:"proxy.process.cluster.vc_cache_lookup_lock_misses"`
    ProxyProcessClusterVcCacheLookupHits                       float64 `json:"proxy.process.cluster.vc_cache_lookup_hits"`
    ProxyProcessClusterVcCacheLookupMisses                     float64 `json:"proxy.process.cluster.vc_cache_lookup_misses"`
    ProxyProcessClusterVcCacheScans                            float64 `json:"proxy.process.cluster.vc_cache_scans"`
    ProxyProcessClusterVcCacheScanLockMisses                   float64 `json:"proxy.process.cluster.vc_cache_scan_lock_misses"`
    ProxyProcessClusterVcCachePurges                           float64 `json:"proxy.process.cluster.vc_cache_purges"`
    ProxyProcessClusterWriteLockMisses                         float64 `json:"proxy.process.cluster.write_lock_misses"`
    ProxyProcessClusterVcReadListLen                           float64 `json:"proxy.process.cluster.vc_read_list_len"`
    ProxyProcessClusterVcWriteListLen                          float64 `json:"proxy.process.cluster.vc_write_list_len"`
}
