type Counters struct {
	proxy_node_restarts_manager_start_time                               float64 `json:"proxy.node.restarts.manager.start_time"`
	proxy_node_restarts_proxy_start_time                                 float64 `json:"proxy.node.restarts.proxy.start_time"`
	proxy_node_restarts_proxy_cache_ready_time                           float64 `json:"proxy.node.restarts.proxy.cache_ready_time"`
	proxy_node_restarts_proxy_stop_time                                  float64 `json:"proxy.node.restarts.proxy.stop_time"`
	proxy_node_restarts_proxy_restart_count                              float64 `json:"proxy.node.restarts.proxy.restart_count"`
	proxy_process_ssl_total_success_handshake_count                      float64 `json:"proxy.process.ssl.total_success_handshake_count"`
	proxy_process_http_completed_requests                                float64 `json:"proxy.process.http.completed_requests"`
	proxy_process_http_total_incoming_connections                        float64 `json:"proxy.process.http.total_incoming_connections"`
	proxy_process_http_total_client_connections                          float64 `json:"proxy.process.http.total_client_connections"`
	proxy_process_http_total_client_connections_ipv4                     float64 `json:"proxy.process.http.total_client_connections_ipv4"`
	proxy_process_http_total_client_connections_ipv6                     float64 `json:"proxy.process.http.total_client_connections_ipv6"`
	proxy_process_http_total_server_connections                          float64 `json:"proxy.process.http.total_server_connections"`
	proxy_process_http_total_parent_proxy_connections                    float64 `json:"proxy.process.http.total_parent_proxy_connections"`
	proxy_process_http_total_parent_retries                              float64 `json:"proxy.process.http.total_parent_retries"`
	proxy_process_http_total_parent_switches                             float64 `json:"proxy.process.http.total_parent_switches"`
	proxy_process_http_total_parent_retries_exhausted                    float64 `json:"proxy.process.http.total_parent_retries_exhausted"`
	proxy_process_http_total_parent_marked_down_count                    float64 `json:"proxy.process.http.total_parent_marked_down_count"`
	proxy_process_http_transaction_counts_errors_pre_accept_hangups      float64 `json:"proxy.process.http.transaction_counts.errors.pre_accept_hangups"`
	proxy_process_http_transaction_totaltime_errors_pre_accept_hangups   float64 `json:"proxy.process.http.transaction_totaltime.errors.pre_accept_hangups"`
	proxy_process_http_incoming_requests                                 float64 `json:"proxy.process.http.incoming_requests"`
	proxy_process_http_outgoing_requests                                 float64 `json:"proxy.process.http.outgoing_requests"`
	proxy_process_http_incoming_responses                                float64 `json:"proxy.process.http.incoming_responses"`
	proxy_process_http_invalid_client_requests                           float64 `json:"proxy.process.http.invalid_client_requests"`
	proxy_process_http_missing_host_hdr                                  float64 `json:"proxy.process.http.missing_host_hdr"`
	proxy_process_http_get_requests                                      float64 `json:"proxy.process.http.get_requests"`
	proxy_process_http_head_requests                                     float64 `json:"proxy.process.http.head_requests"`
	proxy_process_http_trace_requests                                    float64 `json:"proxy.process.http.trace_requests"`
	proxy_process_http_options_requests                                  float64 `json:"proxy.process.http.options_requests"`
	proxy_process_http_post_requests                                     float64 `json:"proxy.process.http.post_requests"`
	proxy_process_http_put_requests                                      float64 `json:"proxy.process.http.put_requests"`
	proxy_process_http_push_requests                                     float64 `json:"proxy.process.http.push_requests"`
	proxy_process_http_delete_requests                                   float64 `json:"proxy.process.http.delete_requests"`
	proxy_process_http_purge_requests                                    float64 `json:"proxy.process.http.purge_requests"`
	proxy_process_http_connect_requests                                  float64 `json:"proxy.process.http.connect_requests"`
	proxy_process_http_extension_method_requests                         float64 `json:"proxy.process.http.extension_method_requests"`
	proxy_process_http_broken_server_connections                         float64 `json:"proxy.process.http.broken_server_connections"`
	proxy_process_http_cache_lookups                                     float64 `json:"proxy.process.http.cache_lookups"`
	proxy_process_http_cache_writes                                      float64 `json:"proxy.process.http.cache_writes"`
	proxy_process_http_cache_updates                                     float64 `json:"proxy.process.http.cache_updates"`
	proxy_process_http_cache_deletes                                     float64 `json:"proxy.process.http.cache_deletes"`
	proxy_process_http_tunnels                                           float64 `json:"proxy.process.http.tunnels"`
	proxy_process_http_throttled_proxy_only                              float64 `json:"proxy.process.http.throttled_proxy_only"`
	proxy_process_http_parent_proxy_transaction_time                     float64 `json:"proxy.process.http.parent_proxy_transaction_time"`
	proxy_process_http_user_agent_request_header_total_size              float64 `json:"proxy.process.http.user_agent_request_header_total_size"`
	proxy_process_http_user_agent_response_header_total_size             float64 `json:"proxy.process.http.user_agent_response_header_total_size"`
	proxy_process_http_user_agent_request_document_total_size            float64 `json:"proxy.process.http.user_agent_request_document_total_size"`
	proxy_process_http_user_agent_response_document_total_size           float64 `json:"proxy.process.http.user_agent_response_document_total_size"`
	proxy_process_http_origin_server_request_header_total_size           float64 `json:"proxy.process.http.origin_server_request_header_total_size"`
	proxy_process_http_origin_server_response_header_total_size          float64 `json:"proxy.process.http.origin_server_response_header_total_size"`
	proxy_process_http_origin_server_request_document_total_size         float64 `json:"proxy.process.http.origin_server_request_document_total_size"`
	proxy_process_http_origin_server_response_document_total_size        float64 `json:"proxy.process.http.origin_server_response_document_total_size"`
	proxy_process_http_parent_proxy_request_total_bytes                  float64 `json:"proxy.process.http.parent_proxy_request_total_bytes"`
	proxy_process_http_parent_proxy_response_total_bytes                 float64 `json:"proxy.process.http.parent_proxy_response_total_bytes"`
	proxy_process_http_pushed_response_header_total_size                 float64 `json:"proxy.process.http.pushed_response_header_total_size"`
	proxy_process_http_pushed_document_total_size                        float64 `json:"proxy.process.http.pushed_document_total_size"`
	proxy_process_http_total_transactions_time                           float64 `json:"proxy.process.http.total_transactions_time"`
	proxy_process_http_cache_hit_fresh                                   float64 `json:"proxy.process.http.cache_hit_fresh"`
	proxy_process_http_cache_hit_mem_fresh                               float64 `json:"proxy.process.http.cache_hit_mem_fresh"`
	proxy_process_http_cache_hit_revalidated                             float64 `json:"proxy.process.http.cache_hit_revalidated"`
	proxy_process_http_cache_hit_ims                                     float64 `json:"proxy.process.http.cache_hit_ims"`
	proxy_process_http_cache_hit_stale_served                            float64 `json:"proxy.process.http.cache_hit_stale_served"`
	proxy_process_http_cache_miss_cold                                   float64 `json:"proxy.process.http.cache_miss_cold"`
	proxy_process_http_cache_miss_changed                                float64 `json:"proxy.process.http.cache_miss_changed"`
	proxy_process_http_cache_miss_client_no_cache                        float64 `json:"proxy.process.http.cache_miss_client_no_cache"`
	proxy_process_http_cache_miss_client_not_cacheable                   float64 `json:"proxy.process.http.cache_miss_client_not_cacheable"`
	proxy_process_http_cache_miss_ims                                    float64 `json:"proxy.process.http.cache_miss_ims"`
	proxy_process_http_cache_read_error                                  float64 `json:"proxy.process.http.cache_read_error"`
	proxy_process_http_tcp_hit_count_stat                                float64 `json:"proxy.process.http.tcp_hit_count_stat"`
	proxy_process_http_tcp_hit_user_agent_bytes_stat                     float64 `json:"proxy.process.http.tcp_hit_user_agent_bytes_stat"`
	proxy_process_http_tcp_hit_origin_server_bytes_stat                  float64 `json:"proxy.process.http.tcp_hit_origin_server_bytes_stat"`
	proxy_process_http_tcp_miss_count_stat                               float64 `json:"proxy.process.http.tcp_miss_count_stat"`
	proxy_process_http_tcp_miss_user_agent_bytes_stat                    float64 `json:"proxy.process.http.tcp_miss_user_agent_bytes_stat"`
	proxy_process_http_tcp_miss_origin_server_bytes_stat                 float64 `json:"proxy.process.http.tcp_miss_origin_server_bytes_stat"`
	proxy_process_http_tcp_expired_miss_count_stat                       float64 `json:"proxy.process.http.tcp_expired_miss_count_stat"`
	proxy_process_http_tcp_expired_miss_user_agent_bytes_stat            float64 `json:"proxy.process.http.tcp_expired_miss_user_agent_bytes_stat"`
	proxy_process_http_tcp_expired_miss_origin_server_bytes_stat         float64 `json:"proxy.process.http.tcp_expired_miss_origin_server_bytes_stat"`
	proxy_process_http_tcp_refresh_hit_count_stat                        float64 `json:"proxy.process.http.tcp_refresh_hit_count_stat"`
	proxy_process_http_tcp_refresh_hit_user_agent_bytes_stat             float64 `json:"proxy.process.http.tcp_refresh_hit_user_agent_bytes_stat"`
	proxy_process_http_tcp_refresh_hit_origin_server_bytes_stat          float64 `json:"proxy.process.http.tcp_refresh_hit_origin_server_bytes_stat"`
	proxy_process_http_tcp_refresh_miss_count_stat                       float64 `json:"proxy.process.http.tcp_refresh_miss_count_stat"`
	proxy_process_http_tcp_refresh_miss_user_agent_bytes_stat            float64 `json:"proxy.process.http.tcp_refresh_miss_user_agent_bytes_stat"`
	proxy_process_http_tcp_refresh_miss_origin_server_bytes_stat         float64 `json:"proxy.process.http.tcp_refresh_miss_origin_server_bytes_stat"`
	proxy_process_http_tcp_client_refresh_count_stat                     float64 `json:"proxy.process.http.tcp_client_refresh_count_stat"`
	proxy_process_http_tcp_client_refresh_user_agent_bytes_stat          float64 `json:"proxy.process.http.tcp_client_refresh_user_agent_bytes_stat"`
	proxy_process_http_tcp_client_refresh_origin_server_bytes_stat       float64 `json:"proxy.process.http.tcp_client_refresh_origin_server_bytes_stat"`
	proxy_process_http_tcp_ims_hit_count_stat                            float64 `json:"proxy.process.http.tcp_ims_hit_count_stat"`
	proxy_process_http_tcp_ims_hit_user_agent_bytes_stat                 float64 `json:"proxy.process.http.tcp_ims_hit_user_agent_bytes_stat"`
	proxy_process_http_tcp_ims_hit_origin_server_bytes_stat              float64 `json:"proxy.process.http.tcp_ims_hit_origin_server_bytes_stat"`
	proxy_process_http_tcp_ims_miss_count_stat                           float64 `json:"proxy.process.http.tcp_ims_miss_count_stat"`
	proxy_process_http_tcp_ims_miss_user_agent_bytes_stat                float64 `json:"proxy.process.http.tcp_ims_miss_user_agent_bytes_stat"`
	proxy_process_http_tcp_ims_miss_origin_server_bytes_stat             float64 `json:"proxy.process.http.tcp_ims_miss_origin_server_bytes_stat"`
	proxy_process_http_err_client_abort_count_stat                       float64 `json:"proxy.process.http.err_client_abort_count_stat"`
	proxy_process_http_err_client_abort_user_agent_bytes_stat            float64 `json:"proxy.process.http.err_client_abort_user_agent_bytes_stat"`
	proxy_process_http_err_client_abort_origin_server_bytes_stat         float64 `json:"proxy.process.http.err_client_abort_origin_server_bytes_stat"`
	proxy_process_http_err_connect_fail_count_stat                       float64 `json:"proxy.process.http.err_connect_fail_count_stat"`
	proxy_process_http_err_connect_fail_user_agent_bytes_stat            float64 `json:"proxy.process.http.err_connect_fail_user_agent_bytes_stat"`
	proxy_process_http_err_connect_fail_origin_server_bytes_stat         float64 `json:"proxy.process.http.err_connect_fail_origin_server_bytes_stat"`
	proxy_process_http_misc_count_stat                                   float64 `json:"proxy.process.http.misc_count_stat"`
	proxy_process_http_misc_user_agent_bytes_stat                        float64 `json:"proxy.process.http.misc_user_agent_bytes_stat"`
	proxy_process_http_http_misc_origin_server_bytes_stat                float64 `json:"proxy.process.http.http_misc_origin_server_bytes_stat"`
	proxy_process_http_background_fill_bytes_aborted_stat                float64 `json:"proxy.process.http.background_fill_bytes_aborted_stat"`
	proxy_process_http_background_fill_bytes_completed_stat              float64 `json:"proxy.process.http.background_fill_bytes_completed_stat"`
	proxy_process_http_cache_write_errors                                float64 `json:"proxy.process.http.cache_write_errors"`
	proxy_process_http_cache_read_errors                                 float64 `json:"proxy.process.http.cache_read_errors"`
	proxy_process_http_100_responses                                     float64 `json:"proxy.process.http.100_responses"`
	proxy_process_http_101_responses                                     float64 `json:"proxy.process.http.101_responses"`
	proxy_process_http_1xx_responses                                     float64 `json:"proxy.process.http.1xx_responses"`
	proxy_process_http_200_responses                                     float64 `json:"proxy.process.http.200_responses"`
	proxy_process_http_201_responses                                     float64 `json:"proxy.process.http.201_responses"`
	proxy_process_http_202_responses                                     float64 `json:"proxy.process.http.202_responses"`
	proxy_process_http_203_responses                                     float64 `json:"proxy.process.http.203_responses"`
	proxy_process_http_204_responses                                     float64 `json:"proxy.process.http.204_responses"`
	proxy_process_http_205_responses                                     float64 `json:"proxy.process.http.205_responses"`
	proxy_process_http_206_responses                                     float64 `json:"proxy.process.http.206_responses"`
	proxy_process_http_2xx_responses                                     float64 `json:"proxy.process.http.2xx_responses"`
	proxy_process_http_300_responses                                     float64 `json:"proxy.process.http.300_responses"`
	proxy_process_http_301_responses                                     float64 `json:"proxy.process.http.301_responses"`
	proxy_process_http_302_responses                                     float64 `json:"proxy.process.http.302_responses"`
	proxy_process_http_303_responses                                     float64 `json:"proxy.process.http.303_responses"`
	proxy_process_http_304_responses                                     float64 `json:"proxy.process.http.304_responses"`
	proxy_process_http_305_responses                                     float64 `json:"proxy.process.http.305_responses"`
	proxy_process_http_307_responses                                     float64 `json:"proxy.process.http.307_responses"`
	proxy_process_http_3xx_responses                                     float64 `json:"proxy.process.http.3xx_responses"`
	proxy_process_http_400_responses                                     float64 `json:"proxy.process.http.400_responses"`
	proxy_process_http_401_responses                                     float64 `json:"proxy.process.http.401_responses"`
	proxy_process_http_402_responses                                     float64 `json:"proxy.process.http.402_responses"`
	proxy_process_http_403_responses                                     float64 `json:"proxy.process.http.403_responses"`
	proxy_process_http_404_responses                                     float64 `json:"proxy.process.http.404_responses"`
	proxy_process_http_405_responses                                     float64 `json:"proxy.process.http.405_responses"`
	proxy_process_http_406_responses                                     float64 `json:"proxy.process.http.406_responses"`
	proxy_process_http_407_responses                                     float64 `json:"proxy.process.http.407_responses"`
	proxy_process_http_408_responses                                     float64 `json:"proxy.process.http.408_responses"`
	proxy_process_http_409_responses                                     float64 `json:"proxy.process.http.409_responses"`
	proxy_process_http_410_responses                                     float64 `json:"proxy.process.http.410_responses"`
	proxy_process_http_411_responses                                     float64 `json:"proxy.process.http.411_responses"`
	proxy_process_http_412_responses                                     float64 `json:"proxy.process.http.412_responses"`
	proxy_process_http_413_responses                                     float64 `json:"proxy.process.http.413_responses"`
	proxy_process_http_414_responses                                     float64 `json:"proxy.process.http.414_responses"`
	proxy_process_http_415_responses                                     float64 `json:"proxy.process.http.415_responses"`
	proxy_process_http_416_responses                                     float64 `json:"proxy.process.http.416_responses"`
	proxy_process_http_4xx_responses                                     float64 `json:"proxy.process.http.4xx_responses"`
	proxy_process_http_500_responses                                     float64 `json:"proxy.process.http.500_responses"`
	proxy_process_http_501_responses                                     float64 `json:"proxy.process.http.501_responses"`
	proxy_process_http_502_responses                                     float64 `json:"proxy.process.http.502_responses"`
	proxy_process_http_503_responses                                     float64 `json:"proxy.process.http.503_responses"`
	proxy_process_http_504_responses                                     float64 `json:"proxy.process.http.504_responses"`
	proxy_process_http_505_responses                                     float64 `json:"proxy.process.http.505_responses"`
	proxy_process_http_5xx_responses                                     float64 `json:"proxy.process.http.5xx_responses"`
	proxy_process_http_transaction_counts_hit_fresh                      float64 `json:"proxy.process.http.transaction_counts.hit_fresh"`
	proxy_process_http_transaction_totaltime_hit_fresh                   float64 `json:"proxy.process.http.transaction_totaltime.hit_fresh"`
	proxy_process_http_transaction_counts_hit_fresh_process              float64 `json:"proxy.process.http.transaction_counts.hit_fresh.process"`
	proxy_process_http_transaction_totaltime_hit_fresh_process           float64 `json:"proxy.process.http.transaction_totaltime.hit_fresh.process"`
	proxy_process_http_transaction_counts_hit_revalidated                float64 `json:"proxy.process.http.transaction_counts.hit_revalidated"`
	proxy_process_http_transaction_totaltime_hit_revalidated             float64 `json:"proxy.process.http.transaction_totaltime.hit_revalidated"`
	proxy_process_http_transaction_counts_miss_cold                      float64 `json:"proxy.process.http.transaction_counts.miss_cold"`
	proxy_process_http_transaction_totaltime_miss_cold                   float64 `json:"proxy.process.http.transaction_totaltime.miss_cold"`
	proxy_process_http_transaction_counts_miss_not_cacheable             float64 `json:"proxy.process.http.transaction_counts.miss_not_cacheable"`
	proxy_process_http_transaction_totaltime_miss_not_cacheable          float64 `json:"proxy.process.http.transaction_totaltime.miss_not_cacheable"`
	proxy_process_http_transaction_counts_miss_changed                   float64 `json:"proxy.process.http.transaction_counts.miss_changed"`
	proxy_process_http_transaction_totaltime_miss_changed                float64 `json:"proxy.process.http.transaction_totaltime.miss_changed"`
	proxy_process_http_transaction_counts_miss_client_no_cache           float64 `json:"proxy.process.http.transaction_counts.miss_client_no_cache"`
	proxy_process_http_transaction_totaltime_miss_client_no_cache        float64 `json:"proxy.process.http.transaction_totaltime.miss_client_no_cache"`
	proxy_process_http_transaction_counts_errors_aborts                  float64 `json:"proxy.process.http.transaction_counts.errors.aborts"`
	proxy_process_http_transaction_totaltime_errors_aborts               float64 `json:"proxy.process.http.transaction_totaltime.errors.aborts"`
	proxy_process_http_transaction_counts_errors_possible_aborts         float64 `json:"proxy.process.http.transaction_counts.errors.possible_aborts"`
	proxy_process_http_transaction_totaltime_errors_possible_aborts      float64 `json:"proxy.process.http.transaction_totaltime.errors.possible_aborts"`
	proxy_process_http_transaction_counts_errors_connect_failed          float64 `json:"proxy.process.http.transaction_counts.errors.connect_failed"`
	proxy_process_http_transaction_totaltime_errors_connect_failed       float64 `json:"proxy.process.http.transaction_totaltime.errors.connect_failed"`
	proxy_process_http_transaction_counts_errors_other                   float64 `json:"proxy.process.http.transaction_counts.errors.other"`
	proxy_process_http_transaction_totaltime_errors_other                float64 `json:"proxy.process.http.transaction_totaltime.errors.other"`
	proxy_process_http_transaction_counts_other_unclassified             float64 `json:"proxy.process.http.transaction_counts.other.unclassified"`
	proxy_process_http_transaction_totaltime_other_unclassified          float64 `json:"proxy.process.http.transaction_totaltime.other.unclassified"`
	proxy_process_http_disallowed_post_100_continue                      float64 `json:"proxy.process.http.disallowed_post_100_continue"`
	proxy_process_http_total_x_redirect_count                            float64 `json:"proxy.process.http.total_x_redirect_count"`
	proxy_process_https_incoming_requests                                float64 `json:"proxy.process.https.incoming_requests"`
	proxy_process_https_total_client_connections                         float64 `json:"proxy.process.https.total_client_connections"`
	proxy_process_http_origin_connections_throttled_out                  float64 `json:"proxy.process.http.origin_connections_throttled_out"`
	proxy_process_http_post_body_too_large                               float64 `json:"proxy.process.http.post_body_too_large"`
	proxy_process_http_milestone_ua_begin                                float64 `json:"proxy.process.http.milestone.ua_begin"`
	proxy_process_http_milestone_ua_first_read                           float64 `json:"proxy.process.http.milestone.ua_first_read"`
	proxy_process_http_milestone_ua_read_header_done                     float64 `json:"proxy.process.http.milestone.ua_read_header_done"`
	proxy_process_http_milestone_ua_begin_write                          float64 `json:"proxy.process.http.milestone.ua_begin_write"`
	proxy_process_http_milestone_ua_close                                float64 `json:"proxy.process.http.milestone.ua_close"`
	proxy_process_http_milestone_server_first_connect                    float64 `json:"proxy.process.http.milestone.server_first_connect"`
	proxy_process_http_milestone_server_connect                          float64 `json:"proxy.process.http.milestone.server_connect"`
	proxy_process_http_milestone_server_connect_end                      float64 `json:"proxy.process.http.milestone.server_connect_end"`
	proxy_process_http_milestone_server_begin_write                      float64 `json:"proxy.process.http.milestone.server_begin_write"`
	proxy_process_http_milestone_server_first_read                       float64 `json:"proxy.process.http.milestone.server_first_read"`
	proxy_process_http_milestone_server_read_header_done                 float64 `json:"proxy.process.http.milestone.server_read_header_done"`
	proxy_process_http_milestone_server_close                            float64 `json:"proxy.process.http.milestone.server_close"`
	proxy_process_http_milestone_cache_open_read_begin                   float64 `json:"proxy.process.http.milestone.cache_open_read_begin"`
	proxy_process_http_milestone_cache_open_read_end                     float64 `json:"proxy.process.http.milestone.cache_open_read_end"`
	proxy_process_http_milestone_cache_open_write_begin                  float64 `json:"proxy.process.http.milestone.cache_open_write_begin"`
	proxy_process_http_milestone_cache_open_write_end                    float64 `json:"proxy.process.http.milestone.cache_open_write_end"`
	proxy_process_http_milestone_dns_lookup_begin                        float64 `json:"proxy.process.http.milestone.dns_lookup_begin"`
	proxy_process_http_milestone_dns_lookup_end                          float64 `json:"proxy.process.http.milestone.dns_lookup_end"`
	proxy_process_http_milestone_sm_start                                float64 `json:"proxy.process.http.milestone.sm_start"`
	proxy_process_http_milestone_sm_finish                               float64 `json:"proxy.process.http.milestone.sm_finish"`
	proxy_process_net_calls_to_read                                      float64 `json:"proxy.process.net.calls_to_read"`
	proxy_process_net_calls_to_read_nodata                               float64 `json:"proxy.process.net.calls_to_read_nodata"`
	proxy_process_net_calls_to_readfromnet                               float64 `json:"proxy.process.net.calls_to_readfromnet"`
	proxy_process_net_calls_to_readfromnet_afterpoll                     float64 `json:"proxy.process.net.calls_to_readfromnet_afterpoll"`
	proxy_process_net_calls_to_write                                     float64 `json:"proxy.process.net.calls_to_write"`
	proxy_process_net_calls_to_write_nodata                              float64 `json:"proxy.process.net.calls_to_write_nodata"`
	proxy_process_net_calls_to_writetonet                                float64 `json:"proxy.process.net.calls_to_writetonet"`
	proxy_process_net_calls_to_writetonet_afterpoll                      float64 `json:"proxy.process.net.calls_to_writetonet_afterpoll"`
	proxy_process_net_inactivity_cop_lock_acquire_failure                float64 `json:"proxy.process.net.inactivity_cop_lock_acquire_failure"`
	proxy_process_net_net_handler_run                                    float64 `json:"proxy.process.net.net_handler_run"`
	proxy_process_net_read_bytes                                         float64 `json:"proxy.process.net.read_bytes"`
	proxy_process_net_write_bytes                                        float64 `json:"proxy.process.net.write_bytes"`
	proxy_process_net_fastopen_out_attempts                              float64 `json:"proxy.process.net.fastopen_out.attempts"`
	proxy_process_net_fastopen_out_successes                             float64 `json:"proxy.process.net.fastopen_out.successes"`
	proxy_process_socks_connections_successful                           float64 `json:"proxy.process.socks.connections_successful"`
	proxy_process_socks_connections_unsuccessful                         float64 `json:"proxy.process.socks.connections_unsuccessful"`
	proxy_process_cache_read_per_sec                                     float64 `json:"proxy.process.cache.read_per_sec"`
	proxy_process_cache_write_per_sec                                    float64 `json:"proxy.process.cache.write_per_sec"`
	proxy_process_cache_KB_read_per_sec                                  float64 `json:"proxy.process.cache.KB_read_per_sec"`
	proxy_process_cache_KB_write_per_sec                                 float64 `json:"proxy.process.cache.KB_write_per_sec"`
	proxy_process_hostdb_total_lookups                                   float64 `json:"proxy.process.hostdb.total_lookups"`
	proxy_process_hostdb_total_hits                                      float64 `json:"proxy.process.hostdb.total_hits"`
	proxy_process_hostdb_ttl                                             float64 `json:"proxy.process.hostdb.ttl"`
	proxy_process_hostdb_ttl_expires                                     float64 `json:"proxy.process.hostdb.ttl_expires"`
	proxy_process_hostdb_re_dns_on_reload                                float64 `json:"proxy.process.hostdb.re_dns_on_reload"`
	proxy_process_dns_total_dns_lookups                                  float64 `json:"proxy.process.dns.total_dns_lookups"`
	proxy_process_dns_lookup_successes                                   float64 `json:"proxy.process.dns.lookup_successes"`
	proxy_process_dns_lookup_failures                                    float64 `json:"proxy.process.dns.lookup_failures"`
	proxy_process_dns_retries                                            float64 `json:"proxy.process.dns.retries"`
	proxy_process_dns_max_retries_exceeded                               float64 `json:"proxy.process.dns.max_retries_exceeded"`
	proxy_process_http2_total_client_streams                             float64 `json:"proxy.process.http2.total_client_streams"`
	proxy_process_http2_total_transactions_time                          float64 `json:"proxy.process.http2.total_transactions_time"`
	proxy_process_http2_total_client_connections                         float64 `json:"proxy.process.http2.total_client_connections"`
	proxy_process_http2_connection_errors                                float64 `json:"proxy.process.http2.connection_errors"`
	proxy_process_http2_stream_errors                                    float64 `json:"proxy.process.http2.stream_errors"`
	proxy_process_http2_session_die_default                              float64 `json:"proxy.process.http2.session_die_default"`
	proxy_process_http2_session_die_other                                float64 `json:"proxy.process.http2.session_die_other"`
	proxy_process_http2_session_die_eos                                  float64 `json:"proxy.process.http2.session_die_eos"`
	proxy_process_http2_session_die_active                               float64 `json:"proxy.process.http2.session_die_active"`
	proxy_process_http2_session_die_inactive                             float64 `json:"proxy.process.http2.session_die_inactive"`
	proxy_process_http2_session_die_error                                float64 `json:"proxy.process.http2.session_die_error"`
	proxy_process_log_event_log_error_ok                                 float64 `json:"proxy.process.log.event_log_error_ok"`
	proxy_process_log_event_log_error_skip                               float64 `json:"proxy.process.log.event_log_error_skip"`
	proxy_process_log_event_log_error_aggr                               float64 `json:"proxy.process.log.event_log_error_aggr"`
	proxy_process_log_event_log_error_full                               float64 `json:"proxy.process.log.event_log_error_full"`
	proxy_process_log_event_log_error_fail                               float64 `json:"proxy.process.log.event_log_error_fail"`
	proxy_process_log_event_log_access_ok                                float64 `json:"proxy.process.log.event_log_access_ok"`
	proxy_process_log_event_log_access_skip                              float64 `json:"proxy.process.log.event_log_access_skip"`
	proxy_process_log_event_log_access_aggr                              float64 `json:"proxy.process.log.event_log_access_aggr"`
	proxy_process_log_event_log_access_full                              float64 `json:"proxy.process.log.event_log_access_full"`
	proxy_process_log_event_log_access_fail                              float64 `json:"proxy.process.log.event_log_access_fail"`
	proxy_process_log_num_sent_to_network                                float64 `json:"proxy.process.log.num_sent_to_network"`
	proxy_process_log_num_lost_before_sent_to_network                    float64 `json:"proxy.process.log.num_lost_before_sent_to_network"`
	proxy_process_log_num_received_from_network                          float64 `json:"proxy.process.log.num_received_from_network"`
	proxy_process_log_num_flush_to_disk                                  float64 `json:"proxy.process.log.num_flush_to_disk"`
	proxy_process_log_num_lost_before_flush_to_disk                      float64 `json:"proxy.process.log.num_lost_before_flush_to_disk"`
	proxy_process_log_bytes_lost_before_preproc                          float64 `json:"proxy.process.log.bytes_lost_before_preproc"`
	proxy_process_log_bytes_sent_to_network                              float64 `json:"proxy.process.log.bytes_sent_to_network"`
	proxy_process_log_bytes_lost_before_sent_to_network                  float64 `json:"proxy.process.log.bytes_lost_before_sent_to_network"`
	proxy_process_log_bytes_received_from_network                        float64 `json:"proxy.process.log.bytes_received_from_network"`
	proxy_process_log_bytes_flush_to_disk                                float64 `json:"proxy.process.log.bytes_flush_to_disk"`
	proxy_process_log_bytes_lost_before_flush_to_disk                    float64 `json:"proxy.process.log.bytes_lost_before_flush_to_disk"`
	proxy_process_log_bytes_written_to_disk                              float64 `json:"proxy.process.log.bytes_written_to_disk"`
	proxy_process_log_bytes_lost_before_written_to_disk                  float64 `json:"proxy.process.log.bytes_lost_before_written_to_disk"`
	proxy_node_config_reconfigure_time                                   float64 `json:"proxy.node.config.reconfigure_time"`
	proxy_node_http_user_agents_total_documents_served                   float64 `json:"proxy.node.http.user_agents_total_documents_served"`
	proxy_node_http_user_agents_total_transactions_count                 float64 `json:"proxy.node.http.user_agents_total_transactions_count"`
	proxy_node_http_origin_server_total_transactions_count               float64 `json:"proxy.node.http.origin_server_total_transactions_count"`
	proxy_node_cache_bytes_total                                         float64 `json:"proxy.node.cache.bytes_total"`
	proxy_node_dns_total_dns_lookups                                     float64 `json:"proxy.node.dns.total_dns_lookups"`
	proxy_node_hostdb_total_lookups                                      float64 `json:"proxy.node.hostdb.total_lookups"`
	proxy_node_hostdb_total_hits                                         float64 `json:"proxy.node.hostdb.total_hits"`
	proxy_node_cluster_nodes                                             float64 `json:"proxy.node.cluster.nodes"`
	proxy_node_http_cache_lookups                                        float64 `json:"proxy.node.http.cache_lookups"`
	proxy_node_http_cache_writes                                         float64 `json:"proxy.node.http.cache_writes"`
	proxy_node_http_cache_updates                                        float64 `json:"proxy.node.http.cache_updates"`
	proxy_node_http_cache_deletes                                        float64 `json:"proxy.node.http.cache_deletes"`
	proxy_node_http_cache_hit_fresh                                      float64 `json:"proxy.node.http.cache_hit_fresh"`
	proxy_node_http_cache_hit_mem_fresh                                  float64 `json:"proxy.node.http.cache_hit_mem_fresh"`
	proxy_node_http_cache_hit_revalidated                                float64 `json:"proxy.node.http.cache_hit_revalidated"`
	proxy_node_http_cache_hit_ims                                        float64 `json:"proxy.node.http.cache_hit_ims"`
	proxy_node_http_cache_hit_stale_served                               float64 `json:"proxy.node.http.cache_hit_stale_served"`
	proxy_node_http_cache_miss_cold                                      float64 `json:"proxy.node.http.cache_miss_cold"`
	proxy_node_http_cache_miss_changed                                   float64 `json:"proxy.node.http.cache_miss_changed"`
	proxy_node_http_cache_miss_client_no_cache                           float64 `json:"proxy.node.http.cache_miss_client_no_cache"`
	proxy_node_http_cache_miss_client_not_cacheable                      float64 `json:"proxy.node.http.cache_miss_client_not_cacheable"`
	proxy_node_http_cache_miss_ims                                       float64 `json:"proxy.node.http.cache_miss_ims"`
	proxy_node_http_cache_read_error                                     float64 `json:"proxy.node.http.cache_read_error"`
	proxy_node_http_cache_write_errors                                   float64 `json:"proxy.node.http.cache_write_errors"`
	proxy_node_http_cache_read_errors                                    float64 `json:"proxy.node.http.cache_read_errors"`
	proxy_node_user_agents_total_documents_served                        float64 `json:"proxy.node.user_agents_total_documents_served"`
	proxy_node_http_user_agent_total_request_bytes                       float64 `json:"proxy.node.http.user_agent_total_request_bytes"`
	proxy_node_http_user_agent_total_response_bytes                      float64 `json:"proxy.node.http.user_agent_total_response_bytes"`
	proxy_node_http_origin_server_total_request_bytes                    float64 `json:"proxy.node.http.origin_server_total_request_bytes"`
	proxy_node_http_origin_server_total_response_bytes                   float64 `json:"proxy.node.http.origin_server_total_response_bytes"`
	proxy_node_http_parent_proxy_total_request_bytes                     float64 `json:"proxy.node.http.parent_proxy_total_request_bytes"`
	proxy_node_http_parent_proxy_total_response_bytes                    float64 `json:"proxy.node.http.parent_proxy_total_response_bytes"`
	proxy_node_user_agent_total_bytes                                    float64 `json:"proxy.node.user_agent_total_bytes"`
	proxy_node_origin_server_total_bytes                                 float64 `json:"proxy.node.origin_server_total_bytes"`
	proxy_node_bandwidth_hit_ratio                                       float64 `json:"proxy.node.bandwidth_hit_ratio"`
	proxy_node_http_throughput                                           float64 `json:"proxy.node.http.throughput"`
	proxy_node_client_throughput_out                                     float64 `json:"proxy.node.client_throughput_out"`
	proxy_node_cache_total_hits                                          float64 `json:"proxy.node.cache_total_hits"`
	proxy_node_cache_total_hits_mem                                      float64 `json:"proxy.node.cache_total_hits_mem"`
	proxy_node_cache_total_misses                                        float64 `json:"proxy.node.cache_total_misses"`
	proxy_node_cache_hit_ratio                                           float64 `json:"proxy.node.cache_hit_ratio"`
	proxy_node_cache_hit_mem_ratio                                       float64 `json:"proxy.node.cache_hit_mem_ratio"`
	proxy_node_cache_bytes_free                                          float64 `json:"proxy.node.cache.bytes_free"`
	proxy_node_cache_percent_free                                        float64 `json:"proxy.node.cache.percent_free"`
	proxy_node_client_throughput_out_kbit                                float64 `json:"proxy.node.client_throughput_out_kbit"`
	proxy_node_cache_bytes_total_mb                                      float64 `json:"proxy.node.cache.bytes_total_mb"`
	proxy_node_cache_bytes_free_mb                                       float64 `json:"proxy.node.cache.bytes_free_mb"`
	proxy_node_log_event_log_access_ok                                   float64 `json:"proxy.node.log.event_log_access_ok"`
	proxy_node_log_event_log_access_skip                                 float64 `json:"proxy.node.log.event_log_access_skip"`
	proxy_node_log_event_log_access_aggr                                 float64 `json:"proxy.node.log.event_log_access_aggr"`
	proxy_node_log_event_log_access_full                                 float64 `json:"proxy.node.log.event_log_access_full"`
	proxy_node_log_event_log_access_fail                                 float64 `json:"proxy.node.log.event_log_access_fail"`
	proxy_node_log_num_lost_before_sent_to_network                       float64 `json:"proxy.node.log.num_lost_before_sent_to_network"`
	proxy_node_log_num_sent_to_network                                   float64 `json:"proxy.node.log.num_sent_to_network"`
	proxy_node_log_bytes_lost_before_sent_to_network                     float64 `json:"proxy.node.log.bytes_lost_before_sent_to_network"`
	proxy_node_log_bytes_sent_to_network                                 float64 `json:"proxy.node.log.bytes_sent_to_network"`
	proxy_node_log_num_received_from_network                             float64 `json:"proxy.node.log.num_received_from_network"`
	proxy_node_log_bytes_received_from_network                           float64 `json:"proxy.node.log.bytes_received_from_network"`
	proxy_node_log_bytes_lost_before_preproc                             float64 `json:"proxy.node.log.bytes_lost_before_preproc"`
	proxy_node_log_num_lost_before_flush_to_disk                         float64 `json:"proxy.node.log.num_lost_before_flush_to_disk"`
	proxy_node_log_bytes_lost_before_flush_to_disk                       float64 `json:"proxy.node.log.bytes_lost_before_flush_to_disk"`
	proxy_node_log_bytes_lost_before_written_to_disk                     float64 `json:"proxy.node.log.bytes_lost_before_written_to_disk"`
	proxy_process_net_default_inactivity_timeout_applied                 float64 `json:"proxy.process.net.default_inactivity_timeout_applied"`
	proxy_process_net_dynamic_keep_alive_timeout_in_count                float64 `json:"proxy.process.net.dynamic_keep_alive_timeout_in_count"`
	proxy_process_net_dynamic_keep_alive_timeout_in_total                float64 `json:"proxy.process.net.dynamic_keep_alive_timeout_in_total"`
	proxy_process_cache_bytes_used                                       float64 `json:"proxy.process.cache.bytes_used"`
	proxy_process_cache_bytes_total                                      float64 `json:"proxy.process.cache.bytes_total"`
	proxy_process_cache_ram_cache_total_bytes                            float64 `json:"proxy.process.cache.ram_cache.total_bytes"`
	proxy_process_cache_ram_cache_bytes_used                             float64 `json:"proxy.process.cache.ram_cache.bytes_used"`
	proxy_process_cache_ram_cache_hits                                   float64 `json:"proxy.process.cache.ram_cache.hits"`
	proxy_process_cache_ram_cache_misses                                 float64 `json:"proxy.process.cache.ram_cache.misses"`
	proxy_process_cache_pread_count                                      float64 `json:"proxy.process.cache.pread_count"`
	proxy_process_cache_percent_full                                     float64 `json:"proxy.process.cache.percent_full"`
	proxy_process_cache_lookup_active                                    float64 `json:"proxy.process.cache.lookup.active"`
	proxy_process_cache_lookup_success                                   float64 `json:"proxy.process.cache.lookup.success"`
	proxy_process_cache_lookup_failure                                   float64 `json:"proxy.process.cache.lookup.failure"`
	proxy_process_cache_read_active                                      float64 `json:"proxy.process.cache.read.active"`
	proxy_process_cache_read_success                                     float64 `json:"proxy.process.cache.read.success"`
	proxy_process_cache_read_failure                                     float64 `json:"proxy.process.cache.read.failure"`
	proxy_process_cache_write_active                                     float64 `json:"proxy.process.cache.write.active"`
	proxy_process_cache_write_success                                    float64 `json:"proxy.process.cache.write.success"`
	proxy_process_cache_write_failure                                    float64 `json:"proxy.process.cache.write.failure"`
	proxy_process_cache_write_backlog_failure                            float64 `json:"proxy.process.cache.write.backlog.failure"`
	proxy_process_cache_update_active                                    float64 `json:"proxy.process.cache.update.active"`
	proxy_process_cache_update_success                                   float64 `json:"proxy.process.cache.update.success"`
	proxy_process_cache_update_failure                                   float64 `json:"proxy.process.cache.update.failure"`
	proxy_process_cache_remove_active                                    float64 `json:"proxy.process.cache.remove.active"`
	proxy_process_cache_remove_success                                   float64 `json:"proxy.process.cache.remove.success"`
	proxy_process_cache_remove_failure                                   float64 `json:"proxy.process.cache.remove.failure"`
	proxy_process_cache_evacuate_active                                  float64 `json:"proxy.process.cache.evacuate.active"`
	proxy_process_cache_evacuate_success                                 float64 `json:"proxy.process.cache.evacuate.success"`
	proxy_process_cache_evacuate_failure                                 float64 `json:"proxy.process.cache.evacuate.failure"`
	proxy_process_cache_scan_active                                      float64 `json:"proxy.process.cache.scan.active"`
	proxy_process_cache_scan_success                                     float64 `json:"proxy.process.cache.scan.success"`
	proxy_process_cache_scan_failure                                     float64 `json:"proxy.process.cache.scan.failure"`
	proxy_process_cache_direntries_total                                 float64 `json:"proxy.process.cache.direntries.total"`
	proxy_process_cache_direntries_used                                  float64 `json:"proxy.process.cache.direntries.used"`
	proxy_process_cache_directory_collision                              float64 `json:"proxy.process.cache.directory_collision"`
	proxy_process_cache_frags_per_doc_1                                  float64 `json:"proxy.process.cache.frags_per_doc.1"`
	proxy_process_cache_frags_per_doc_2                                  float64 `json:"proxy.process.cache.frags_per_doc.2"`
	proxy_process_cache_frags_per_doc_3_plus                             float64 `json:"proxy.process.cache.frags_per_doc.3+"`
	proxy_process_cache_read_busy_success                                float64 `json:"proxy.process.cache.read_busy.success"`
	proxy_process_cache_read_busy_failure                                float64 `json:"proxy.process.cache.read_busy.failure"`
	proxy_process_cache_write_bytes_stat                                 float64 `json:"proxy.process.cache.write_bytes_stat"`
	proxy_process_cache_vector_marshals                                  float64 `json:"proxy.process.cache.vector_marshals"`
	proxy_process_cache_hdr_marshals                                     float64 `json:"proxy.process.cache.hdr_marshals"`
	proxy_process_cache_hdr_marshal_bytes                                float64 `json:"proxy.process.cache.hdr_marshal_bytes"`
	proxy_process_cache_gc_bytes_evacuated                               float64 `json:"proxy.process.cache.gc_bytes_evacuated"`
	proxy_process_cache_gc_frags_evacuated                               float64 `json:"proxy.process.cache.gc_frags_evacuated"`
	proxy_process_cache_wrap_count                                       float64 `json:"proxy.process.cache.wrap_count"`
	proxy_process_cache_sync_count                                       float64 `json:"proxy.process.cache.sync.count"`
	proxy_process_cache_sync_bytes                                       float64 `json:"proxy.process.cache.sync.bytes"`
	proxy_process_cache_sync_time                                        float64 `json:"proxy.process.cache.sync.time"`
	proxy_process_cache_span_errors_read                                 float64 `json:"proxy.process.cache.span.errors.read"`
	proxy_process_cache_span_errors_write                                float64 `json:"proxy.process.cache.span.errors.write"`
	proxy_process_cache_span_failing                                     float64 `json:"proxy.process.cache.span.failing"`
	proxy_process_cache_span_offline                                     float64 `json:"proxy.process.cache.span.offline"`
	proxy_process_cache_span_online                                      float64 `json:"proxy.process.cache.span.online"`
	proxy_process_dns_in_flight                                          float64 `json:"proxy.process.dns.in_flight"`
	proxy_process_congestion_congested_on_conn_failures                  float64 `json:"proxy.process.congestion.congested_on_conn_failures"`
	proxy_process_congestion_congested_on_max_connection                 float64 `json:"proxy.process.congestion.congested_on_max_connection"`
	proxy_process_hostdb_cache_total_inserts                             float64 `json:"proxy.process.hostdb.cache.total_inserts"`
	proxy_process_hostdb_cache_total_failed_inserts                      float64 `json:"proxy.process.hostdb.cache.total_failed_inserts"`
	proxy_process_hostdb_cache_total_lookups                             float64 `json:"proxy.process.hostdb.cache.total_lookups"`
	proxy_process_hostdb_cache_total_hits                                float64 `json:"proxy.process.hostdb.cache.total_hits"`
	proxy_process_hostdb_cache_last_sync_time                            float64 `json:"proxy.process.hostdb.cache.last_sync.time"`
	proxy_process_hostdb_cache_last_sync_total_items                     float64 `json:"proxy.process.hostdb.cache.last_sync.total_items"`
	proxy_process_hostdb_cache_last_sync_total_size                      float64 `json:"proxy.process.hostdb.cache.last_sync.total_size"`
}
