
type Gauges struct {
    proxy_process_cache_read_per_sec                                     float64 `json:"proxy.process.cache.read_per_sec"`
    proxy_process_cache_write_per_sec                                    float64 `json:"proxy.process.cache.write_per_sec"`
    proxy_process_cache_KB_read_per_sec                                  float64 `json:"proxy.process.cache.KB_read_per_sec"`
    proxy_process_cache_KB_write_per_sec                                 float64 `json:"proxy.process.cache.KB_write_per_sec"`
	proxy_process_http_avg_transactions_per_client_connection            float64 `json:"proxy.process.http.avg_transactions_per_client_connection"`
	proxy_process_http_avg_transactions_per_server_connection            float64 `json:"proxy.process.http.avg_transactions_per_server_connection"`
	proxy_process_dns_lookup_avg_time                                    float64 `json:"proxy.process.dns.lookup_avg_time"`
	proxy_process_dns_fail_avg_time                                      float64 `json:"proxy.process.dns.fail_avg_time"`
    proxy_node_http_cache_current_connections_count                      float64 `json:"proxy.node.http.cache_current_connections_count"`
    proxy_node_http_user_agent_current_connections_count                 float64 `json:"proxy.node.http.user_agent_current_connections_count"`
    proxy_node_http_origin_server_current_connections_count              float64 `json:"proxy.node.http.origin_server_current_connections_count"`
	proxy_node_proxy_running                                             float64 `json:"proxy_node.proxy_running"`
	proxy_node_config_reconfigure_required                               float64 `json:"proxy.node.config.reconfigure_required"`
    proxy_node_config_restart_required_proxy                             float64 `json:"proxy.node.config.restart_required.proxy"`
    proxy_node_config_restart_required_manager                           float64 `json:"proxy.node.config.restart_required.manager"`
    proxy_node_config_restart_required_cop                               float64 `json:"proxy.node.config.restart_required.cop"`
	proxy_node_http_user_agent_xacts_per_second                          float64 `json:"proxy.node.http.user_agent_xacts_per_second"`
	proxy_node_user_agent_xacts_per_second                               float64 `json:"proxy.node.user_agent_xacts_per_second"`
    proxy_node_dns_lookups_per_second                                    float64 `json:"proxy.node.dns.lookups_per_second"`
    proxy_node_hostdb_total_lookups_avg_10s                              float64 `json:"proxy.node.hostdb.total_lookups_avg_10s"`
    proxy_node_hostdb_total_hits_avg_10s                                 float64 `json:"proxy.node.hostdb.total_hits_avg_10s"`
    proxy_node_hostdb_hit_ratio_avg_10s                                  float64 `json:"proxy.node.hostdb.hit_ratio_avg_10s"`
    proxy_node_hostdb_hit_ratio                                          float64 `json:"proxy.node.hostdb.hit_ratio"`
	proxy_node_log_bytes_sent_to_network_avg_10s                         float64 `json:"proxy.node.log.bytes_sent_to_network_avg_10s"`
	proxy_node_log_bytes_received_from_network_avg_10s                   float64 `json:"proxy.node.log.bytes_received_from_network_avg_10s"`
    proxy_node_user_agent_total_bytes_avg_10s                            float64 `json:"proxy.node.user_agent_total_bytes_avg_10s"`
    proxy_node_origin_server_total_bytes_avg_10s                         float64 `json:"proxy.node.origin_server_total_bytes_avg_10s"`
    proxy_node_bandwidth_hit_ratio_avg_10s                               float64 `json:"proxy.node.bandwidth_hit_ratio_avg_10s"`
    proxy_node_http_cache_hit_fresh_avg_10s                              float64 `json:"proxy.node.http.cache_hit_fresh_avg_10s"`
    proxy_node_http_cache_hit_mem_fresh_avg_10s                          float64 `json:"proxy.node.http.cache_hit_mem_fresh_avg_10s"`
    proxy_node_http_cache_hit_revalidated_avg_10s                        float64 `json:"proxy.node.http.cache_hit_revalidated_avg_10s"`
    proxy_node_http_cache_hit_ims_avg_10s                                float64 `json:"proxy.node.http.cache_hit_ims_avg_10s"`
    proxy_node_http_cache_hit_stale_served_avg_10s                       float64 `json:"proxy.node.http.cache_hit_stale_served_avg_10s"`
    proxy_node_http_cache_miss_cold_avg_10s                              float64 `json:"proxy.node.http.cache_miss_cold_avg_10s"`
    proxy_node_http_cache_miss_changed_avg_10s                           float64 `json:"proxy.node.http.cache_miss_changed_avg_10s"`
    proxy_node_http_cache_miss_client_no_cache_avg_10s                   float64 `json:"proxy.node.http.cache_miss_client_no_cache_avg_10s"`
    proxy_node_http_cache_miss_ims_avg_10s                               float64 `json:"proxy.node.http.cache_miss_ims_avg_10s"`
    proxy_node_http_cache_read_error_avg_10s                             float64 `json:"proxy.node.http.cache_read_error_avg_10s"`
    proxy_node_cache_total_hits_avg_10s                                  float64 `json:"proxy.node.cache_total_hits_avg_10s"`
    proxy_node_cache_total_hits_mem_avg_10s                              float64 `json:"proxy.node.cache_total_hits_mem_avg_10s"`
    proxy_node_cache_total_misses_avg_10s                                float64 `json:"proxy.node.cache_total_misses_avg_10s"`
    proxy_node_cache_hit_ratio_avg_10s                                   float64 `json:"proxy.node.cache_hit_ratio_avg_10s"`
    proxy_node_cache_hit_mem_ratio_avg_10s                               float64 `json:"proxy.node.cache_hit_mem_ratio_avg_10s"`
    proxy_node_http_transaction_counts_avg_10s_hit_fresh                 float64 `json:"proxy.node.http.transaction_counts_avg_10s.hit_fresh"`
    proxy_node_http_transaction_counts_avg_10s_hit_revalidated           float64 `json:"proxy.node.http.transaction_counts_avg_10s.hit_revalidated"`
    proxy_node_http_transaction_counts_avg_10s_miss_cold                 float64 `json:"proxy.node.http.transaction_counts_avg_10s.miss_cold"`
    proxy_node_http_transaction_counts_avg_10s_miss_changed              float64 `json:"proxy.node.http.transaction_counts_avg_10s.miss_changed"`
    proxy_node_http_transaction_counts_avg_10s_miss_client_no_cache      float64 `json:"proxy.node.http.transaction_counts_avg_10s.miss_client_no_cache"`
    proxy_node_http_transaction_counts_avg_10s_miss_not_cacheable        float64 `json:"proxy.node.http.transaction_counts_avg_10s.miss_not_cacheable"`
    proxy_node_http_transaction_counts_avg_10s_errors_connect_failed     float64 `json:"proxy.node.http.transaction_counts_avg_10s.errors.connect_failed"`
    proxy_node_http_transaction_counts_avg_10s_errors_aborts             float64 `json:"proxy.node.http.transaction_counts_avg_10s.errors.aborts"`
    proxy_node_http_transaction_counts_avg_10s_errors_possible_aborts    float64 `json:"proxy.node.http.transaction_counts_avg_10s.errors.possible_aborts"`
    proxy_node_http_transaction_counts_avg_10s_errors_pre_accept_hangups float64 `json:"proxy.node.http.transaction_counts_avg_10s.errors.pre_accept_hangups"`
    proxy_node_http_transaction_counts_avg_10s_errors_other              float64 `json:"proxy.node.http.transaction_counts_avg_10s.errors.other"`
    proxy_node_http_transaction_frac_avg_10s_hit_fresh                   float64 `json:"proxy.node.http.transaction_frac_avg_10s.hit_fresh"`
    proxy_node_http_transaction_frac_avg_10s_hit_revalidated             float64 `json:"proxy.node.http.transaction_frac_avg_10s.hit_revalidated"`
    proxy_node_http_transaction_frac_avg_10s_miss_cold                   float64 `json:"proxy.node.http.transaction_frac_avg_10s.miss_cold"`
    proxy_node_http_transaction_frac_avg_10s_miss_changed                float64 `json:"proxy.node.http.transaction_frac_avg_10s.miss_changed"`
    proxy_node_http_transaction_frac_avg_10s_miss_client_no_cache        float64 `json:"proxy.node.http.transaction_frac_avg_10s.miss_client_no_cache"`
    proxy_node_http_transaction_frac_avg_10s_miss_not_cacheable          float64 `json:"proxy.node.http.transaction_frac_avg_10s.miss_not_cacheable"`
    proxy_node_http_current_parent_proxy_connections                     float64 `json:"proxy.node.http.current_parent_proxy_connections"`
    proxy_node_http_transaction_frac_avg_10s_errors_connect_failed       float64 `json:"proxy.node.http.transaction_frac_avg_10s.errors.connect_failed"`
    proxy_node_http_transaction_frac_avg_10s_errors_aborts               float64 `json:"proxy.node.http.transaction_frac_avg_10s.errors.aborts"`
    proxy_node_http_transaction_frac_avg_10s_errors_possible_aborts      float64 `json:"proxy.node.http.transaction_frac_avg_10s.errors.possible_aborts"`
    proxy_node_http_transaction_frac_avg_10s_errors_pre_accept_hangups   float64 `json:"proxy.node.http.transaction_frac_avg_10s.errors.pre_accept_hangups"`
    proxy_node_http_transaction_frac_avg_10s_errors_other                float64 `json:"proxy.node.http.transaction_frac_avg_10s.errors.other"`
    proxy_node_http_transaction_msec_avg_10s_hit_fresh                   float64 `json:"proxy.node.http.transaction_msec_avg_10s.hit_fresh"`
    proxy_node_http_transaction_msec_avg_10s_hit_revalidated             float64 `json:"proxy.node.http.transaction_msec_avg_10s.hit_revalidated"`
    proxy_node_http_transaction_msec_avg_10s_miss_cold                   float64 `json:"proxy.node.http.transaction_msec_avg_10s.miss_cold"`
    proxy_node_http_transaction_msec_avg_10s_miss_changed                float64 `json:"proxy.node.http.transaction_msec_avg_10s.miss_changed"`
    proxy_node_http_transaction_msec_avg_10s_miss_client_no_cache        float64 `json:"proxy.node.http.transaction_msec_avg_10s.miss_client_no_cache"`
    proxy_node_http_transaction_msec_avg_10s_miss_not_cacheable          float64 `json:"proxy.node.http.transaction_msec_avg_10s.miss_not_cacheable"`
    proxy_node_http_transaction_msec_avg_10s_errors_connect_failed       float64 `json:"proxy.node.http.transaction_msec_avg_10s.errors.connect_failed"`
    proxy_node_http_transaction_msec_avg_10s_errors_aborts               float64 `json:"proxy.node.http.transaction_msec_avg_10s.errors.aborts"`
    proxy_node_http_transaction_msec_avg_10s_errors_possible_aborts      float64 `json:"proxy.node.http.transaction_msec_avg_10s.errors.possible_aborts"`
    proxy_node_http_transaction_msec_avg_10s_errors_pre_accept_hangups   float64 `json:"proxy.node.http.transaction_msec_avg_10s.errors.pre_accept_hangups"`
    proxy_node_http_transaction_msec_avg_10s_errors_other                float64 `json:"proxy.node.http.transaction_msec_avg_10s.errors.other"`
    proxy_node_current_client_connections                                float64 `json:"proxy.node.current_client_connections"`
    proxy_node_current_server_connections                                float64 `json:"proxy.node.current_server_connections"`
    proxy_node_current_cache_connections                                 float64 `json:"proxy.node.current_cache_connections"`
	proxy_process_socks_connections_currently_open                       float64 `json:"proxy.process.socks.connections_currently_open"`
    proxy_process_http_background_fill_current_count                     float64 `json:"proxy.process.http.background_fill_current_count"`
    proxy_process_http_current_client_connections                        float64 `json:"proxy.process.http.current_client_connections"`
    proxy_process_http_current_active_client_connections                 float64 `json:"proxy.process.http.current_active_client_connections"`
    proxy_process_http_websocket_current_active_client_connections       float64 `json:"proxy.process.http.websocket.current_active_client_connections"`
    proxy_process_http_current_client_transactions                       float64 `json:"proxy.process.http.current_client_transactions"`
    proxy_process_http_current_server_transactions                       float64 `json:"proxy.process.http.current_server_transactions"`
    proxy_process_http_current_parent_proxy_connections                  float64 `json:"proxy.process.http.current_parent_proxy_connections"`
    proxy_process_http_current_server_connections                        float64 `json:"proxy.process.http.current_server_connections"`
    proxy_process_http_current_cache_connections                         float64 `json:"proxy.process.http.current_cache_connections"`
    proxy_process_net_accepts_currently_open                             float64 `json:"proxy.process.net.accepts_currently_open"`
    proxy_process_net_connections_currently_open                         float64 `json:"proxy.process.net.connections_currently_open"`
    proxy_process_http2_current_client_sessions                          float64 `json:"proxy.process.http2.current_client_sessions"`
    proxy_process_http2_current_client_streams                           float64 `json:"proxy.process.http2.current_client_streams"`
    proxy_process_hostdb_cache_current_items                             float64 `json:"proxy.process.hostdb.cache.current_items"`
    proxy_process_hostdb_cache_current_size                              float64 `json:"proxy.process.hostdb.cache.current_size"`
	proxy_process_dns_success_avg_time                                   float64 `json:"proxy.process.dns.success_avg_time"`
    proxy_process_log_log_files_open                                     float64 `json:"proxy.process.log.log_files_open"`
    proxy_process_log_log_files_space_used                               float64 `json:"proxy.process.log.log_files_space_used"`
}
