    proxy_process_http_response_document_size_100                        float64 `json:"proxy.process.http.response_document_size_100"`
    proxy_process_http_response_document_size_1K                         float64 `json:"proxy.process.http.response_document_size_1K"`
    proxy_process_http_response_document_size_3K                         float64 `json:"proxy.process.http.response_document_size_3K"`
    proxy_process_http_response_document_size_5K                         float64 `json:"proxy.process.http.response_document_size_5K"`
    proxy_process_http_response_document_size_10K                        float64 `json:"proxy.process.http.response_document_size_10K"`
    proxy_process_http_response_document_size_1M                         float64 `json:"proxy.process.http.response_document_size_1M"`
    proxy_process_http_response_document_size_inf                        float64 `json:"proxy.process.http.response_document_size_inf"`
    proxy_process_http_request_document_size_100                         float64 `json:"proxy.process.http.request_document_size_100"`
    proxy_process_http_request_document_size_1K                          float64 `json:"proxy.process.http.request_document_size_1K"`
    proxy_process_http_request_document_size_3K                          float64 `json:"proxy.process.http.request_document_size_3K"`
    proxy_process_http_request_document_size_5K                          float64 `json:"proxy.process.http.request_document_size_5K"`
    proxy_process_http_request_document_size_10K                         float64 `json:"proxy.process.http.request_document_size_10K"`
    proxy_process_http_request_document_size_1M                          float64 `json:"proxy.process.http.request_document_size_1M"`
    proxy_process_http_request_document_size_inf                         float64 `json:"proxy.process.http.request_document_size_inf"`
    proxy_process_http_user_agent_speed_bytes_per_sec_100                float64 `json:"proxy.process.http.user_agent_speed_bytes_per_sec_100"`
    proxy_process_http_user_agent_speed_bytes_per_sec_1K                 float64 `json:"proxy.process.http.user_agent_speed_bytes_per_sec_1K"`
    proxy_process_http_user_agent_speed_bytes_per_sec_10K                float64 `json:"proxy.process.http.user_agent_speed_bytes_per_sec_10K"`
    proxy_process_http_user_agent_speed_bytes_per_sec_100K               float64 `json:"proxy.process.http.user_agent_speed_bytes_per_sec_100K"`
    proxy_process_http_user_agent_speed_bytes_per_sec_1M                 float64 `json:"proxy.process.http.user_agent_speed_bytes_per_sec_1M"`
    proxy_process_http_user_agent_speed_bytes_per_sec_10M                float64 `json:"proxy.process.http.user_agent_speed_bytes_per_sec_10M"`
    proxy_process_http_user_agent_speed_bytes_per_sec_100M               float64 `json:"proxy.process.http.user_agent_speed_bytes_per_sec_100M"`
    proxy_process_http_origin_server_speed_bytes_per_sec_100             float64 `json:"proxy.process.http.origin_server_speed_bytes_per_sec_100"`
    proxy_process_http_origin_server_speed_bytes_per_sec_1K              float64 `json:"proxy.process.http.origin_server_speed_bytes_per_sec_1K"`
    proxy_process_http_origin_server_speed_bytes_per_sec_10K             float64 `json:"proxy.process.http.origin_server_speed_bytes_per_sec_10K"`
    proxy_process_http_origin_server_speed_bytes_per_sec_100K            float64 `json:"proxy.process.http.origin_server_speed_bytes_per_sec_100K"`
    proxy_process_http_origin_server_speed_bytes_per_sec_1M              float64 `json:"proxy.process.http.origin_server_speed_bytes_per_sec_1M"`
    proxy_process_http_origin_server_speed_bytes_per_sec_10M             float64 `json:"proxy.process.http.origin_server_speed_bytes_per_sec_10M"`
    proxy_process_http_origin_server_speed_bytes_per_sec_100M            float64 `json:"proxy.process.http.origin_server_speed_bytes_per_sec_100M"`
