package ssl_structs

type SSLCounters struct {
    // We don't care a ton about SSL here, so ignore for now.
    //ProxyProcessSslUserAgentOtherErrors                        float64 `json:"proxy.process.ssl.user_agent_other_errors"`
    //ProxyProcessSslUserAgentExpiredCert                        float64 `json:"proxy.process.ssl.user_agent_expired_cert"`
    //ProxyProcessSslUserAgentRevokedCert                        float64 `json:"proxy.process.ssl.user_agent_revoked_cert"`
    //ProxyProcessSslUserAgentUnknownCert                        float64 `json:"proxy.process.ssl.user_agent_unknown_cert"`
    //ProxyProcessSslUserAgentCertVerifyFailed                   float64 `json:"proxy.process.ssl.user_agent_cert_verify_failed"`
    //ProxyProcessSslUserAgentBadCert                            float64 `json:"proxy.process.ssl.user_agent_bad_cert"`
    //ProxyProcessSslUserAgentDecryptionFailed                   float64 `json:"proxy.process.ssl.user_agent_decryption_failed"`
    //ProxyProcessSslUserAgentWrongVersion                       float64 `json:"proxy.process.ssl.user_agent_wrong_version"`
    //ProxyProcessSslUserAgentUnknownCa                          float64 `json:"proxy.process.ssl.user_agent_unknown_ca"`
    //ProxyProcessSslOriginServerOtherErrors                     float64 `json:"proxy.process.ssl.origin_server_other_errors"`
    //ProxyProcessSslOriginServerExpiredCert                     float64 `json:"proxy.process.ssl.origin_server_expired_cert"`
    //ProxyProcessSslOriginServerRevokedCert                     float64 `json:"proxy.process.ssl.origin_server_revoked_cert"`
    //ProxyProcessSslOriginServerUnknownCert                     float64 `json:"proxy.process.ssl.origin_server_unknown_cert"`
    //ProxyProcessSslOriginServerCertVerifyFailed                float64 `json:"proxy.process.ssl.origin_server_cert_verify_failed"`
    //ProxyProcessSslOriginServerBadCert                         float64 `json:"proxy.process.ssl.origin_server_bad_cert"`
    //ProxyProcessSslOriginServerDecryptionFailed                float64 `json:"proxy.process.ssl.origin_server_decryption_failed"`
    //ProxyProcessSslOriginServerWrongVersion                    float64 `json:"proxy.process.ssl.origin_server_wrong_version"`
    //ProxyProcessSslOriginServerUnknownCa                       float64 `json:"proxy.process.ssl.origin_server_unknown_ca"`
    //ProxyProcessSslTotalHandshakeTime                          float64 `json:"proxy.process.ssl.total_handshake_time"`
    //ProxyProcessSslTotalSuccessHandshakeCountIn                float64 `json:"proxy.process.ssl.total_success_handshake_count_in"`
    //ProxyProcessSslTotalSuccessHandshakeCountOut               float64 `json:"proxy.process.ssl.total_success_handshake_count_out"`
    //ProxyProcessSslTotalTicketsCreated                         float64 `json:"proxy.process.ssl.total_tickets_created"`
    //ProxyProcessSslTotalTicketsVerified                        float64 `json:"proxy.process.ssl.total_tickets_verified"`
    //ProxyProcessSslTotalTicketsNotFound                        float64 `json:"proxy.process.ssl.total_tickets_not_found"`
    //ProxyProcessSslTotalTicketsRenewed                         float64 `json:"proxy.process.ssl.total_tickets_renewed"`
    //ProxyProcessSslTotalTicketsVerifiedOldKey                  float64 `json:"proxy.process.ssl.total_tickets_verified_old_key"`
    //ProxyProcessSslTotalTicketKeysRenewed                      float64 `json:"proxy.process.ssl.total_ticket_keys_renewed"`
    //ProxyProcessSslSslSessionCacheHit                          float64 `json:"proxy.process.ssl.ssl_session_cache_hit"`
    //ProxyProcessSslSslSessionCacheNewSession                   float64 `json:"proxy.process.ssl.ssl_session_cache_new_session"`
    //ProxyProcessSslSslSessionCacheMiss                         float64 `json:"proxy.process.ssl.ssl_session_cache_miss"`
    //ProxyProcessSslSslSessionCacheEviction                     float64 `json:"proxy.process.ssl.ssl_session_cache_eviction"`
    //ProxyProcessSslSslSessionCacheLockContention               float64 `json:"proxy.process.ssl.ssl_session_cache_lock_contention"`
    //ProxyProcessSslSslErrorWantWrite                           float64 `json:"proxy.process.ssl.ssl_error_want_write"`
    //ProxyProcessSslSslErrorWantRead                            float64 `json:"proxy.process.ssl.ssl_error_want_read"`
    //ProxyProcessSslSslErrorWantX509Lookup                      float64 `json:"proxy.process.ssl.ssl_error_want_x509_lookup"`
    //ProxyProcessSslSslErrorSyscall                             float64 `json:"proxy.process.ssl.ssl_error_syscall"`
    //ProxyProcessSslSslErrorReadEos                             float64 `json:"proxy.process.ssl.ssl_error_read_eos"`
    //ProxyProcessSslSslErrorZeroReturn                          float64 `json:"proxy.process.ssl.ssl_error_zero_return"`
    //ProxyProcessSslSslErrorSsl                                 float64 `json:"proxy.process.ssl.ssl_error_ssl"`
    //ProxyProcessSslSslSniNameSetFailure                        float64 `json:"proxy.process.ssl.ssl_sni_name_set_failure"`
    //ProxyProcessSslSslOcspRevokedCertStat                      float64 `json:"proxy.process.ssl.ssl_ocsp_revoked_cert_stat"`
    //ProxyProcessSslSslOcspUnknownCertStat                      float64 `json:"proxy.process.ssl.ssl_ocsp_unknown_cert_stat"`
    //ProxyProcessSslSslOcspRefreshedCert                        float64 `json:"proxy.process.ssl.ssl_ocsp_refreshed_cert"`
    //ProxyProcessSslSslOcspRefreshCertFailure                   float64 `json:"proxy.process.ssl.ssl_ocsp_refresh_cert_failure"`
    //ProxyProcessSslUserAgentSessions                           float64 `json:"proxy.process.ssl.user_agent_sessions"`
    //ProxyProcessSslUserAgentSessionHit                         float64 `json:"proxy.process.ssl.user_agent_session_hit"`
    //ProxyProcessSslUserAgentSessionMiss                        float64 `json:"proxy.process.ssl.user_agent_session_miss"`
    //ProxyProcessSslUserAgentSessionTimeout                     float64 `json:"proxy.process.ssl.user_agent_session_timeout"`
}

type SSLCypherCounters struct {
    //ProxyProcessSslCipherUserAgentECDHERSAAES256GCMSHA384      float64 `json:"proxy.process.ssl.cipher.user_agent.ECDHE-RSA-AES256-GCM-SHA384"`
    //ProxyProcessSslCipherUserAgentECDHEECDSAAES256GCMSHA384    float64 `json:"proxy.process.ssl.cipher.user_agent.ECDHE-ECDSA-AES256-GCM-SHA384"`
    //ProxyProcessSslCipherUserAgentECDHERSAAES256SHA384         float64 `json:"proxy.process.ssl.cipher.user_agent.ECDHE-RSA-AES256-SHA384"`
    //ProxyProcessSslCipherUserAgentECDHEECDSAAES256SHA384       float64 `json:"proxy.process.ssl.cipher.user_agent.ECDHE-ECDSA-AES256-SHA384"`
    //ProxyProcessSslCipherUserAgentECDHERSAAES256SHA            float64 `json:"proxy.process.ssl.cipher.user_agent.ECDHE-RSA-AES256-SHA"`
    //ProxyProcessSslCipherUserAgentECDHEECDSAAES256SHA          float64 `json:"proxy.process.ssl.cipher.user_agent.ECDHE-ECDSA-AES256-SHA"`
    //ProxyProcessSslCipherUserAgentDHDSSAES256GCMSHA384         float64 `json:"proxy.process.ssl.cipher.user_agent.DH-DSS-AES256-GCM-SHA384"`
    //ProxyProcessSslCipherUserAgentDHEDSSAES256GCMSHA384        float64 `json:"proxy.process.ssl.cipher.user_agent.DHE-DSS-AES256-GCM-SHA384"`
    //ProxyProcessSslCipherUserAgentDHRSAAES256GCMSHA384         float64 `json:"proxy.process.ssl.cipher.user_agent.DH-RSA-AES256-GCM-SHA384"`
    //ProxyProcessSslCipherUserAgentDHERSAAES256GCMSHA384        float64 `json:"proxy.process.ssl.cipher.user_agent.DHE-RSA-AES256-GCM-SHA384"`
    //ProxyProcessSslCipherUserAgentDHERSAAES256SHA256           float64 `json:"proxy.process.ssl.cipher.user_agent.DHE-RSA-AES256-SHA256"`
    //ProxyProcessSslCipherUserAgentDHEDSSAES256SHA256           float64 `json:"proxy.process.ssl.cipher.user_agent.DHE-DSS-AES256-SHA256"`
    //ProxyProcessSslCipherUserAgentDHRSAAES256SHA256            float64 `json:"proxy.process.ssl.cipher.user_agent.DH-RSA-AES256-SHA256"`
    //ProxyProcessSslCipherUserAgentDHDSSAES256SHA256            float64 `json:"proxy.process.ssl.cipher.user_agent.DH-DSS-AES256-SHA256"`
    //ProxyProcessSslCipherUserAgentDHERSAAES256SHA              float64 `json:"proxy.process.ssl.cipher.user_agent.DHE-RSA-AES256-SHA"`
    //ProxyProcessSslCipherUserAgentDHEDSSAES256SHA              float64 `json:"proxy.process.ssl.cipher.user_agent.DHE-DSS-AES256-SHA"`
    //ProxyProcessSslCipherUserAgentDHRSAAES256SHA               float64 `json:"proxy.process.ssl.cipher.user_agent.DH-RSA-AES256-SHA"`
    //ProxyProcessSslCipherUserAgentDHDSSAES256SHA               float64 `json:"proxy.process.ssl.cipher.user_agent.DH-DSS-AES256-SHA"`
    //ProxyProcessSslCipherUserAgentDHERSACAMELLIA256SHA         float64 `json:"proxy.process.ssl.cipher.user_agent.DHE-RSA-CAMELLIA256-SHA"`
    //ProxyProcessSslCipherUserAgentDHEDSSCAMELLIA256SHA         float64 `json:"proxy.process.ssl.cipher.user_agent.DHE-DSS-CAMELLIA256-SHA"`
    //ProxyProcessSslCipherUserAgentDHRSACAMELLIA256SHA          float64 `json:"proxy.process.ssl.cipher.user_agent.DH-RSA-CAMELLIA256-SHA"`
    //ProxyProcessSslCipherUserAgentDHDSSCAMELLIA256SHA          float64 `json:"proxy.process.ssl.cipher.user_agent.DH-DSS-CAMELLIA256-SHA"`
    //ProxyProcessSslCipherUserAgentECDHRSAAES256GCMSHA384       float64 `json:"proxy.process.ssl.cipher.user_agent.ECDH-RSA-AES256-GCM-SHA384"`
    //ProxyProcessSslCipherUserAgentECDHECDSAAES256GCMSHA384     float64 `json:"proxy.process.ssl.cipher.user_agent.ECDH-ECDSA-AES256-GCM-SHA384"`
    //ProxyProcessSslCipherUserAgentECDHRSAAES256SHA384          float64 `json:"proxy.process.ssl.cipher.user_agent.ECDH-RSA-AES256-SHA384"`
    //ProxyProcessSslCipherUserAgentECDHECDSAAES256SHA384        float64 `json:"proxy.process.ssl.cipher.user_agent.ECDH-ECDSA-AES256-SHA384"`
    //ProxyProcessSslCipherUserAgentECDHRSAAES256SHA             float64 `json:"proxy.process.ssl.cipher.user_agent.ECDH-RSA-AES256-SHA"`
    //ProxyProcessSslCipherUserAgentECDHECDSAAES256SHA           float64 `json:"proxy.process.ssl.cipher.user_agent.ECDH-ECDSA-AES256-SHA"`
    //ProxyProcessSslCipherUserAgentAES256GCMSHA384              float64 `json:"proxy.process.ssl.cipher.user_agent.AES256-GCM-SHA384"`
    //ProxyProcessSslCipherUserAgentAES256SHA256                 float64 `json:"proxy.process.ssl.cipher.user_agent.AES256-SHA256"`
    //ProxyProcessSslCipherUserAgentAES256SHA                    float64 `json:"proxy.process.ssl.cipher.user_agent.AES256-SHA"`
    //ProxyProcessSslCipherUserAgentCAMELLIA256SHA               float64 `json:"proxy.process.ssl.cipher.user_agent.CAMELLIA256-SHA"`
    //ProxyProcessSslCipherUserAgentPSKAES256CBCSHA              float64 `json:"proxy.process.ssl.cipher.user_agent.PSK-AES256-CBC-SHA"`
    //ProxyProcessSslCipherUserAgentECDHERSAAES128GCMSHA256      float64 `json:"proxy.process.ssl.cipher.user_agent.ECDHE-RSA-AES128-GCM-SHA256"`
    //ProxyProcessSslCipherUserAgentECDHEECDSAAES128GCMSHA256    float64 `json:"proxy.process.ssl.cipher.user_agent.ECDHE-ECDSA-AES128-GCM-SHA256"`
    //ProxyProcessSslCipherUserAgentECDHERSAAES128SHA256         float64 `json:"proxy.process.ssl.cipher.user_agent.ECDHE-RSA-AES128-SHA256"`
    //ProxyProcessSslCipherUserAgentECDHEECDSAAES128SHA256       float64 `json:"proxy.process.ssl.cipher.user_agent.ECDHE-ECDSA-AES128-SHA256"`
    //ProxyProcessSslCipherUserAgentECDHERSAAES128SHA            float64 `json:"proxy.process.ssl.cipher.user_agent.ECDHE-RSA-AES128-SHA"`
    //ProxyProcessSslCipherUserAgentECDHEECDSAAES128SHA          float64 `json:"proxy.process.ssl.cipher.user_agent.ECDHE-ECDSA-AES128-SHA"`
    //ProxyProcessSslCipherUserAgentDHDSSAES128GCMSHA256         float64 `json:"proxy.process.ssl.cipher.user_agent.DH-DSS-AES128-GCM-SHA256"`
    //ProxyProcessSslCipherUserAgentDHEDSSAES128GCMSHA256        float64 `json:"proxy.process.ssl.cipher.user_agent.DHE-DSS-AES128-GCM-SHA256"`
    //ProxyProcessSslCipherUserAgentDHRSAAES128GCMSHA256         float64 `json:"proxy.process.ssl.cipher.user_agent.DH-RSA-AES128-GCM-SHA256"`
    //ProxyProcessSslCipherUserAgentDHERSAAES128GCMSHA256        float64 `json:"proxy.process.ssl.cipher.user_agent.DHE-RSA-AES128-GCM-SHA256"`
    //ProxyProcessSslCipherUserAgentDHERSAAES128SHA256           float64 `json:"proxy.process.ssl.cipher.user_agent.DHE-RSA-AES128-SHA256"`
    //ProxyProcessSslCipherUserAgentDHEDSSAES128SHA256           float64 `json:"proxy.process.ssl.cipher.user_agent.DHE-DSS-AES128-SHA256"`
    //ProxyProcessSslCipherUserAgentDHRSAAES128SHA256            float64 `json:"proxy.process.ssl.cipher.user_agent.DH-RSA-AES128-SHA256"`
    //ProxyProcessSslCipherUserAgentDHDSSAES128SHA256            float64 `json:"proxy.process.ssl.cipher.user_agent.DH-DSS-AES128-SHA256"`
    //ProxyProcessSslCipherUserAgentDHERSAAES128SHA              float64 `json:"proxy.process.ssl.cipher.user_agent.DHE-RSA-AES128-SHA"`
    //ProxyProcessSslCipherUserAgentDHEDSSAES128SHA              float64 `json:"proxy.process.ssl.cipher.user_agent.DHE-DSS-AES128-SHA"`
    //ProxyProcessSslCipherUserAgentDHRSAAES128SHA               float64 `json:"proxy.process.ssl.cipher.user_agent.DH-RSA-AES128-SHA"`
    //ProxyProcessSslCipherUserAgentDHDSSAES128SHA               float64 `json:"proxy.process.ssl.cipher.user_agent.DH-DSS-AES128-SHA"`
    //ProxyProcessSslCipherUserAgentDHERSASEEDSHA                float64 `json:"proxy.process.ssl.cipher.user_agent.DHE-RSA-SEED-SHA"`
    //ProxyProcessSslCipherUserAgentDHEDSSSEEDSHA                float64 `json:"proxy.process.ssl.cipher.user_agent.DHE-DSS-SEED-SHA"`
    //ProxyProcessSslCipherUserAgentDHRSASEEDSHA                 float64 `json:"proxy.process.ssl.cipher.user_agent.DH-RSA-SEED-SHA"`
    //ProxyProcessSslCipherUserAgentDHDSSSEEDSHA                 float64 `json:"proxy.process.ssl.cipher.user_agent.DH-DSS-SEED-SHA"`
    //ProxyProcessSslCipherUserAgentDHERSACAMELLIA128SHA         float64 `json:"proxy.process.ssl.cipher.user_agent.DHE-RSA-CAMELLIA128-SHA"`
    //ProxyProcessSslCipherUserAgentDHEDSSCAMELLIA128SHA         float64 `json:"proxy.process.ssl.cipher.user_agent.DHE-DSS-CAMELLIA128-SHA"`
    //ProxyProcessSslCipherUserAgentDHRSACAMELLIA128SHA          float64 `json:"proxy.process.ssl.cipher.user_agent.DH-RSA-CAMELLIA128-SHA"`
    //ProxyProcessSslCipherUserAgentDHDSSCAMELLIA128SHA          float64 `json:"proxy.process.ssl.cipher.user_agent.DH-DSS-CAMELLIA128-SHA"`
    //ProxyProcessSslCipherUserAgentECDHRSAAES128GCMSHA256       float64 `json:"proxy.process.ssl.cipher.user_agent.ECDH-RSA-AES128-GCM-SHA256"`
    //ProxyProcessSslCipherUserAgentECDHECDSAAES128GCMSHA256     float64 `json:"proxy.process.ssl.cipher.user_agent.ECDH-ECDSA-AES128-GCM-SHA256"`
    //ProxyProcessSslCipherUserAgentECDHRSAAES128SHA256          float64 `json:"proxy.process.ssl.cipher.user_agent.ECDH-RSA-AES128-SHA256"`
    //ProxyProcessSslCipherUserAgentECDHECDSAAES128SHA256        float64 `json:"proxy.process.ssl.cipher.user_agent.ECDH-ECDSA-AES128-SHA256"`
    //ProxyProcessSslCipherUserAgentECDHRSAAES128SHA             float64 `json:"proxy.process.ssl.cipher.user_agent.ECDH-RSA-AES128-SHA"`
    //ProxyProcessSslCipherUserAgentECDHECDSAAES128SHA           float64 `json:"proxy.process.ssl.cipher.user_agent.ECDH-ECDSA-AES128-SHA"`
    //ProxyProcessSslCipherUserAgentAES128GCMSHA256              float64 `json:"proxy.process.ssl.cipher.user_agent.AES128-GCM-SHA256"`
    //ProxyProcessSslCipherUserAgentAES128SHA256                 float64 `json:"proxy.process.ssl.cipher.user_agent.AES128-SHA256"`
    //ProxyProcessSslCipherUserAgentAES128SHA                    float64 `json:"proxy.process.ssl.cipher.user_agent.AES128-SHA"`
    //ProxyProcessSslCipherUserAgentSEEDSHA                      float64 `json:"proxy.process.ssl.cipher.user_agent.SEED-SHA"`
    //ProxyProcessSslCipherUserAgentCAMELLIA128SHA               float64 `json:"proxy.process.ssl.cipher.user_agent.CAMELLIA128-SHA"`
    //ProxyProcessSslCipherUserAgentPSKAES128CBCSHA              float64 `json:"proxy.process.ssl.cipher.user_agent.PSK-AES128-CBC-SHA"`
    //ProxyProcessSslCipherUserAgentECDHERSADESCBC3SHA           float64 `json:"proxy.process.ssl.cipher.user_agent.ECDHE-RSA-DES-CBC3-SHA"`
    //ProxyProcessSslCipherUserAgentECDHEECDSADESCBC3SHA         float64 `json:"proxy.process.ssl.cipher.user_agent.ECDHE-ECDSA-DES-CBC3-SHA"`
    //ProxyProcessSslCipherUserAgentEDHRSADESCBC3SHA             float64 `json:"proxy.process.ssl.cipher.user_agent.EDH-RSA-DES-CBC3-SHA"`
    //ProxyProcessSslCipherUserAgentEDHDSSDESCBC3SHA             float64 `json:"proxy.process.ssl.cipher.user_agent.EDH-DSS-DES-CBC3-SHA"`
    //ProxyProcessSslCipherUserAgentDHRSADESCBC3SHA              float64 `json:"proxy.process.ssl.cipher.user_agent.DH-RSA-DES-CBC3-SHA"`
    //ProxyProcessSslCipherUserAgentDHDSSDESCBC3SHA              float64 `json:"proxy.process.ssl.cipher.user_agent.DH-DSS-DES-CBC3-SHA"`
    //ProxyProcessSslCipherUserAgentECDHRSADESCBC3SHA            float64 `json:"proxy.process.ssl.cipher.user_agent.ECDH-RSA-DES-CBC3-SHA"`
    //ProxyProcessSslCipherUserAgentECDHECDSADESCBC3SHA          float64 `json:"proxy.process.ssl.cipher.user_agent.ECDH-ECDSA-DES-CBC3-SHA"`
    //ProxyProcessSslCipherUserAgentDESCBC3SHA                   float64 `json:"proxy.process.ssl.cipher.user_agent.DES-CBC3-SHA"`
    //ProxyProcessSslCipherUserAgentIDEACBCSHA                   float64 `json:"proxy.process.ssl.cipher.user_agent.IDEA-CBC-SHA"`
    //ProxyProcessSslCipherUserAgentPSK3DESEDECBCSHA             float64 `json:"proxy.process.ssl.cipher.user_agent.PSK-3DES-EDE-CBC-SHA"`
    //ProxyProcessSslCipherUserAgentKRB5IDEACBCSHA               float64 `json:"proxy.process.ssl.cipher.user_agent.KRB5-IDEA-CBC-SHA"`
    //ProxyProcessSslCipherUserAgentKRB5DESCBC3SHA               float64 `json:"proxy.process.ssl.cipher.user_agent.KRB5-DES-CBC3-SHA"`
    //ProxyProcessSslCipherUserAgentKRB5IDEACBCMD5               float64 `json:"proxy.process.ssl.cipher.user_agent.KRB5-IDEA-CBC-MD5"`
    //ProxyProcessSslCipherUserAgentKRB5DESCBC3MD5               float64 `json:"proxy.process.ssl.cipher.user_agent.KRB5-DES-CBC3-MD5"`
    //ProxyProcessSslCipherUserAgentECDHERSARC4SHA               float64 `json:"proxy.process.ssl.cipher.user_agent.ECDHE-RSA-RC4-SHA"`
    //ProxyProcessSslCipherUserAgentECDHEECDSARC4SHA             float64 `json:"proxy.process.ssl.cipher.user_agent.ECDHE-ECDSA-RC4-SHA"`
    //ProxyProcessSslCipherUserAgentECDHRSARC4SHA                float64 `json:"proxy.process.ssl.cipher.user_agent.ECDH-RSA-RC4-SHA"`
    //ProxyProcessSslCipherUserAgentECDHECDSARC4SHA              float64 `json:"proxy.process.ssl.cipher.user_agent.ECDH-ECDSA-RC4-SHA"`
    //ProxyProcessSslCipherUserAgentRC4SHA                       float64 `json:"proxy.process.ssl.cipher.user_agent.RC4-SHA"`
    //ProxyProcessSslCipherUserAgentRC4MD5                       float64 `json:"proxy.process.ssl.cipher.user_agent.RC4-MD5"`
    //ProxyProcessSslCipherUserAgentPSKRC4SHA                    float64 `json:"proxy.process.ssl.cipher.user_agent.PSK-RC4-SHA"`
    //ProxyProcessSslCipherUserAgentKRB5RC4SHA                   float64 `json:"proxy.process.ssl.cipher.user_agent.KRB5-RC4-SHA"`
    //ProxyProcessSslCipherUserAgentKRB5RC4MD5                   float64 `json:"proxy.process.ssl.cipher.user_agent.KRB5-RC4-MD5"`
}
